name: Submit Dataproc Batch Job

on:
  push:
    branches:
      - main  # Set the branch where this action should run
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ secrets.GCP_SA_EMAIL }}
        workload_identity_provider: 'projects/775224453412/locations/global/workloadIdentityPools/powerbi-monitoring-pool/subject/SUBJECT_ATTRIBUTE_VALUE'
        service_account: ${{ secrets.GCP_SA_KEY }}

    - name: Submit Dataproc Batch
      run: |
        gcloud dataproc batches submit pyspark gs://dataproc-practice-bucket-1/main_job.py \
          --project slot-112 \
          --region us-east1 \
          --batch batch-53c0 \
          --version 2.2 \
          --subnet subnet1

